import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { ApiError, LaterBenderApi } from "./api.js";

const statuses = z.enum(["backlog", "ready", "doing", "done", "dropped"]);
const priorities = z.enum(["low", "normal", "high"]);
const annotations = (write: "read" | "create" | "update") => ({ readOnlyHint: write === "read", destructiveHint: write === "update", idempotentHint: write !== "create", openWorldHint: false });
const output = (root: string) => z.object({ [root]: z.array(z.unknown()) });
const singleOutput = (root: string) => z.object({ [root]: z.unknown() });
const result = (root: string, data: unknown) => ({ content: [{ type: "text" as const, text: JSON.stringify({ [root]: data }) }], structuredContent: { [root]: data } });
const failure = (error: unknown) => { const e = error instanceof ApiError ? error : new ApiError("backend_unavailable", 503, error instanceof Error ? error.message : "Backend unavailable"); return { content: [{ type: "text" as const, text: JSON.stringify({ error: { code: e.code, message: e.message } }) }], structuredContent: { error: { code: e.code, message: e.message } }, isError: true }; };
const safe = (root: string, fn: () => Promise<unknown>) => fn().then((data) => result(root, data)).catch(failure);
const taskFields = { title: z.string().optional(), status: statuses.optional(), priority: priorities.optional(), context: z.string().optional(), intended_direction: z.string().optional(), tags: z.array(z.string()).optional(), related_note_ids: z.array(z.number().int().positive()).optional() };

export function registerTools(server: McpServer, api: LaterBenderApi): void {
  server.registerTool("list_projects", { description: "List projects visible to the authenticated user.", inputSchema: {}, outputSchema: output("projects"), annotations: annotations("read") }, () => safe("projects", () => api.listProjects()));
  server.registerTool("get_project", { description: "Fetch one complete project by its human-readable slug.", inputSchema: { slug: z.string() }, outputSchema: singleOutput("project"), annotations: annotations("read") }, ({ slug }) => safe("project", () => api.getProject(slug)));
  server.registerTool("create_project", { description: "Create a project. Omit slug to let Later Bender generate one from the name.", inputSchema: { name: z.string(), slug: z.string().optional(), description: z.string().optional() }, outputSchema: singleOutput("project"), annotations: annotations("create") }, (input) => safe("project", () => api.createProject(input)));
  server.registerTool("update_project", { description: "Update mutable project fields by slug.", inputSchema: { slug: z.string(), name: z.string().optional(), description: z.string().optional(), archived_at: z.string().nullable().optional() }, outputSchema: singleOutput("project"), annotations: annotations("update") }, ({ slug, ...payload }) => safe("project", () => api.updateProject(slug, payload)));

  server.registerTool("list_tasks", { description: "Browse Tasks in a known project using structured filters. Use search_memory for approximate textual recall or when you do not know whether information is a Task or Note.", inputSchema: { project: z.string(), status: statuses.optional(), priority: priorities.optional(), tag: z.string().optional(), limit: z.number().int().positive().max(100).optional() }, outputSchema: output("tasks"), annotations: annotations("read") }, ({ project, limit, ...filters }) => safe("tasks", () => api.listTasks(project, { ...filters, limit: limit?.toString() })));
  server.registerTool("get_task", { description: "Fetch the complete canonical Task after identifying it by global numeric ID, typically from a list or search result.", inputSchema: { id: z.number().int().positive() }, outputSchema: singleOutput("task"), annotations: annotations("read") }, ({ id }) => safe("task", () => api.getTask(id)));
  server.registerTool("create_task", { description: "Create an actionable Task in a project. Omitted status and priority use Later Bender defaults (backlog and normal). Unknown tags are created automatically. related_note_ids links Notes that materially contributed to or contextualize the Task.", inputSchema: { project: z.string(), title: z.string(), status: statuses.optional(), priority: priorities.optional(), context: z.string().optional(), intended_direction: z.string().optional(), tags: z.array(z.string()).optional(), related_note_ids: z.array(z.number().int().positive()).optional() }, outputSchema: singleOutput("task"), annotations: annotations("create") }, ({ project, ...payload }) => safe("task", () => api.createTask(project, payload)));
  server.registerTool("update_task", { description: "Partially update a Task by global ID. Omitted tags or related_note_ids preserve existing relations; [] clears them; a non-empty array replaces them exactly. Unknown tags are created automatically.", inputSchema: { id: z.number().int().positive(), ...taskFields }, outputSchema: singleOutput("task"), annotations: annotations("update") }, ({ id, ...payload }) => safe("task", () => api.updateTask(id, payload)));

  server.registerTool("list_notes", { description: "Browse compact Note summaries in a known scope. Use search_memory instead for approximate recall.", inputSchema: { scope: z.enum(["global", "project", "all"]).optional(), project: z.string().optional(), tags: z.array(z.string()).optional(), limit: z.number().int().positive().max(100).optional() }, outputSchema: output("notes"), annotations: annotations("read") }, (input) => safe("notes", async () => { if (input.scope === "project" && !input.project) throw new ApiError("validation_failed", 422, "scope=project requires project"); return api.listNotes(input); }));
  server.registerTool("get_note", { description: "Fetch the complete canonical Note after identifying it by global numeric ID, typically from a list or search result.", inputSchema: { id: z.number().int().positive() }, outputSchema: singleOutput("note"), annotations: annotations("read") }, ({ id }) => safe("note", () => api.getNote(id)));
  server.registerTool("create_note", { description: "Store durable non-actionable context such as an idea, decision, finding, constraint, hypothesis, observation, possible direction, or discussion result. Omit project for global context; provide a project slug for project-specific context. Unknown tags are created automatically.", inputSchema: { title: z.string(), body: z.string(), project: z.string().optional(), tags: z.array(z.string()).optional() }, outputSchema: singleOutput("note"), annotations: annotations("create") }, (input) => safe("note", () => api.createNote(input)));
  server.registerTool("update_note", { description: "Partially update a Note by global ID. Omitted project or tags preserve them; project null makes it global; tags [] clears tags and a non-empty array replaces them exactly.", inputSchema: { id: z.number().int().positive(), title: z.string().optional(), body: z.string().optional(), project: z.string().nullable().optional(), tags: z.array(z.string()).optional() }, outputSchema: singleOutput("note"), annotations: annotations("update") }, ({ id, ...payload }) => safe("note", () => api.updateNote(id, payload)));

  server.registerTool("search_memory", { description: "Search Later Bender durable state across Tasks and Notes. Use this for recalling prior decisions, ideas, findings, project context, or work when you may not know where or how it was stored. Results are ranked summaries with matching excerpts; fetch the full Task or Note when exact details are needed.", inputSchema: { query: z.string(), scope: z.enum(["all", "global", "project"]).optional(), project: z.string().optional(), kinds: z.array(z.enum(["task", "note"])).optional(), tags: z.array(z.string()).optional(), task_statuses: z.array(statuses).optional(), task_priorities: z.array(priorities).optional(), limit: z.number().int().positive().max(100).optional() }, outputSchema: output("results"), annotations: annotations("read") }, (input) => safe("results", async () => { if (input.scope === "project" && !input.project) throw new ApiError("validation_failed", 422, "scope=project requires project"); return (await api.searchMemory(input)).results; }));
}
