<script setup>
import { onMounted, ref } from 'vue'; import { request } from '../api'; import { useAuthStore } from '../stores/auth'
const auth=useAuthStore(); const files=ref([]); const projects=ref([]); const project=ref(''); const selected=ref(null); const content=ref(null); const query=ref(''); const error=ref(''); const previewError=ref(''); const loading=ref(true)
async function load(){ loading.value=true; error.value=''; try { projects.value=await request('/projects',{},auth.token); project.value ||= projects.value.find(item=>item.slug==='later-bender')?.slug || projects.value[0]?.slug || ''; if(project.value) files.value=await request(`/projects/${project.value}/files?limit=100`,{},auth.token); await openFromQuery() }catch(e){error.value=e.message}finally{loading.value=false} }
async function open(file){ selected.value=file; content.value=null; error.value=''; previewError.value=''; try { const detail=await request(`/files/by-ref/${encodeURIComponent(file.ref)}`,{},auth.token); selected.value=detail; if (detail.representations?.length) content.value=await request(`/files/by-ref/${encodeURIComponent(file.ref)}/read`,{},auth.token) }catch(e){previewError.value=e.message} }
async function openFromQuery(){ const refFromQuery=new URLSearchParams(window.location.search).get('ref'); const file=files.value.find(item=>item.ref===refFromQuery); if(file) await open(file) }
function filtered(){return files.value.filter(f=>!query.value || `${f.filename} ${f.ref} ${f.media_type}`.toLowerCase().includes(query.value.toLowerCase()))}
onMounted(load)
</script>
<template><section class="surface-page files-page"><header class="page-heading"><div><h1>Files</h1><p>Immutable canonical evidence and artifacts</p></div></header><div class="toolbar"><input v-model="query" placeholder="Filter files…" aria-label="Filter files"><select v-model="project" aria-label="Project" @change="load"><option v-for="p in projects" :key="p.slug" :value="p.slug">{{p.name}}</option></select><span class="muted">Created ↓</span></div><p v-if="loading" class="muted">Loading files…</p><p v-else-if="!filtered().length" class="panel empty-state">No files in this project.</p><div v-else class="file-table panel"><div class="file-head"><span>Ref</span><span>Filename</span><span>Type</span><span>Size</span><span>Related</span></div><button v-for="file in filtered()" :key="file.ref" class="file-row" :class="{selected:selected?.ref===file.ref}" @click="open(file)"><strong>{{file.ref}}</strong><strong>{{file.filename}}</strong><span>{{file.media_type}}</span><span>{{(file.byte_size/1024).toFixed(file.byte_size<1024?0:1)}} KB</span><span>{{file.related_task_refs?.join(', ') || '—'}}</span></button></div><article v-if="selected" class="file-detail panel"><span class="meta">{{selected.ref}}</span><h2>{{selected.filename}}</h2><p class="meta">{{selected.media_type}} · {{selected.byte_size}} bytes · SHA-256 {{selected.sha256?.slice(0,8)}}…</p><h3>Preview</h3><pre v-if="content" class="file-read">{{content.content || content.read?.content || 'No readable content.'}}</pre><p v-else-if="previewError" class="muted">Preview unavailable for this file.</p><p v-else-if="selected.representations?.length" class="muted">Loading preview…</p><p v-else class="muted">No preview is available for this file.</p><div class="relations"><strong>Relations</strong><router-link v-for="ref in selected.related_task_refs" :key="ref" :to="`/tasks/${ref}`" class="pill blue">{{ref}}</router-link><span v-if="!selected.related_task_refs?.length" class="muted">None</span></div></article><p v-if="error" class="error">{{error}}</p></section></template>
