<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { request } from '../api'; import { useAuthStore } from '../stores/auth'
import { renderMarkdown } from '../markdown'
const auth=useAuthStore(); const notes=ref([]); const selected=ref(null); const query=ref(''); const loading=ref(true); const error=ref(''); const saving=ref(false); const draft=ref({title:'',body:''})
const filtered=computed(()=>notes.value.filter(n=>!query.value || `${n.title} ${n.excerpt} ${n.tags?.join(' ')}`.toLowerCase().includes(query.value.toLowerCase())))
 async function load(){ loading.value=true; try { const data=await request('/notes?summary=true&limit=100',{},auth.token); notes.value=data; const requestedId=Number(new URLSearchParams(window.location.search).get('note')); const requested=data.find(note=>note.id===requestedId); if(requested) select(requested); else if(!selected.value && data[0]) select(data[0]) } catch(e){error.value=e.message} finally{loading.value=false} }
async function select(note){ selected.value=note; try { draft.value=await request(`/notes/${note.id}`,{},auth.token) } catch(e){error.value=e.message} }
async function save(){ if(!draft.value.title.trim())return; saving.value=true; try { const saved=await request(`/notes/${draft.value.id}`,{method:'PATCH',body:JSON.stringify({title:draft.value.title,body:draft.value.body})},auth.token); const i=notes.value.findIndex(n=>n.id===saved.id); if(i>=0)notes.value[i]={...notes.value[i],...saved,excerpt:saved.body}; selected.value=notes.value[i]; draft.value=saved } catch(e){error.value=e.message} finally{saving.value=false} }
async function create(){ try { const note=await request('/notes',{method:'POST',body:JSON.stringify({title:'Untitled note',body:''})},auth.token); notes.value.unshift(note); select(note) } catch(e){error.value=e.message} }
watch(query,()=>{}); onMounted(load)
</script>
<template><section class="surface-page notes-page"><header class="page-heading"><div><h1>Notes</h1><p>Durable editable memory, without task lifecycle</p></div><button class="primary" @click="create">+ New note</button></header><div class="notes-layout"><aside class="note-list panel"><input v-model="query" aria-label="Search notes" placeholder="Search notes…"><h2>Notes</h2><p v-if="loading" class="muted">Loading…</p><button v-for="note in filtered" :key="note.id" class="note-row" :class="{selected: selected?.id===note.id}" @click="select(note)"><strong>{{note.title}}</strong><small>{{note.project?.name || 'Global'}} · {{new Date(note.updated_at).toLocaleDateString()}}</small><span>{{note.excerpt || 'No body yet…'}}</span></button></aside><article v-if="draft.id" class="note-editor panel"><input v-model="draft.title" class="editor-title" aria-label="Note title"><p class="meta">{{draft.project?.name || 'Global'}} <span v-for="tag in draft.tags" :key="tag"> · {{tag}}</span></p><hr><div class="note-body-view prose" aria-label="Rendered note" v-html="renderMarkdown(draft.body)"></div><details class="note-source"><summary>Edit Markdown</summary><textarea v-model="draft.body" aria-label="Note body" placeholder="Write durable context…"></textarea></details><footer><span class="muted">Saved to canonical Notes</span><button class="primary" :disabled="saving" @click="save">{{saving?'Saving…':'Save note'}}</button></footer><section class="relations"><strong>Relations</strong><router-link v-for="task in draft.related_tasks" :key="task.id" :to="`/tasks/${task.id}`" class="pill blue">{{task.ref}}</router-link><router-link v-for="file in draft.related_files" :key="file.ref" :to="`/files?ref=${encodeURIComponent(file.ref)}`" class="pill amber">{{file.ref}}</router-link></section></article><div v-else class="panel empty-state">Select a note to edit it.</div></div><p v-if="error" class="error">{{error}}</p></section></template>
