<script setup>
import { computed, onMounted, ref } from 'vue'
import { request } from '../api'
import { useAuthStore } from '../stores/auth'
import '../remote-agents.css'
const auth=useAuthStore(), agents=ref([]), selectedRef=ref(''), loading=ref(true), error=ref(''), enrollment=ref(null), enrollmentLoading=ref(false), renameOpen=ref(false), rename=ref(''), saving=ref(false)
const selected=computed(()=>agents.value.find(a=>a.ref===selectedRef.value)||null)
const knownCapabilityLabels={process_control:'Process control',hardware_access:'Hardware access',isolation:'Isolation'}
const knownCapabilityValues={process_control:{process_group:'Process group',cgroup_v2:'cgroup v2'},hardware_access:{host:'Host',none:'None'},isolation:{none:'None',container:'Container'}}
const humanize=value=>String(value).replace(/[_-]+/g,' ').replace(/\b\w/g,letter=>letter.toUpperCase())
const capabilityFacts=computed(()=>Object.entries(selected.value?.capabilities||{}).map(([key,value])=>({label:knownCapabilityLabels[key]||humanize(key),value:knownCapabilityValues[key]?.[value]||humanize(value)})))
const date=v=>v?new Date(v).toLocaleString():'Never'; const status=a=>a.revoked?'Revoked':a.availability==='online'?'Online':'Offline'
async function load(){loading.value=true;error.value='';try{const d=await request('/remote-agents',{},auth.token);agents.value=d.agents||[];if(!agents.value.some(a=>a.ref===selectedRef.value))selectedRef.value=agents.value[0]?.ref||''}catch(e){error.value=e.message}finally{loading.value=false}}
async function enroll(){enrollmentLoading.value=true;error.value='';try{enrollment.value=await request('/remote-agents/enrollment-tokens',{method:'POST',body:'{}'},auth.token)}catch(e){error.value=e.message}finally{enrollmentLoading.value=false}}
function startRename(){rename.value=selected.value?.name||'';renameOpen.value=true}
async function saveRename(){if(!selected.value||!rename.value.trim())return;saving.value=true;try{const d=await request(`/remote-agents/${encodeURIComponent(selected.value.ref)}`,{method:'PATCH',body:JSON.stringify({name:rename.value.trim()})},auth.token);agents.value=agents.value.map(a=>a.ref===d.agent.ref?d.agent:a);renameOpen.value=false}catch(e){error.value=e.message}finally{saving.value=false}}
async function revoke(){if(!selected.value||!window.confirm(`Revoke ${selected.value.name}? This cannot be undone.`))return;try{await request(`/remote-agents/${encodeURIComponent(selected.value.ref)}/revoke`,{method:'POST',body:'{}'},auth.token);await load()}catch(e){error.value=e.message}}
onMounted(load)
</script>
<template><section class="surface-page agents-page"><header class="page-heading"><div><h1>Remote Agents</h1><p>User-controlled machines available as Workspace execution targets</p></div><button class="primary" :disabled="enrollmentLoading" @click="enroll">{{enrollmentLoading?'Preparing…':'Enroll agent'}}</button></header>
<div v-if="enrollment" class="enrollment panel"><div><strong>Enrollment token ready</strong><p>Use this one-time token with the Remote Agent installer. It expires {{date(enrollment.expires_at)}}.</p></div><code>{{enrollment.token}}</code><button @click="enrollment=null">Dismiss</button></div>
<p v-if="loading" class="muted">Loading Remote Agents…</p><p v-else-if="error" class="error">{{error}} <button @click="load">Retry</button></p>
<template v-else-if="agents.length"><div class="agent-table panel"><div class="agent-head"><span>Name</span><span>Ref</span><span>Status</span><span>Platform</span><span>Executors</span><span>Last seen</span></div><button v-for="agent in agents" :key="agent.ref" class="agent-row" :class="{selected:selectedRef===agent.ref}" @click="selectedRef=agent.ref"><strong>{{agent.name}}</strong><span>{{agent.ref}}</span><span class="agent-status" :class="status(agent).toLowerCase()">{{status(agent)}}</span><span>{{agent.platform}} · {{agent.architecture}}</span><span class="executor-list">{{agent.supported_executors.join(', ')}}</span><span>{{date(agent.last_seen_at)}}</span></button></div>
<div v-if="selected" class="agent-detail"><article class="panel agent-identity"><span class="meta">{{selected.ref}}</span><h2>{{selected.name}}</h2><p class="muted">{{selected.platform}} · {{selected.architecture}} · {{status(selected)}}</p><h3>Capabilities</h3><dl class="agent-capabilities"><div v-for="fact in capabilityFacts" :key="fact.label"><dt>{{fact.label}}</dt><dd>{{fact.value}}</dd></div><p v-if="!capabilityFacts.length" class="muted">No additional capabilities reported.</p></dl><dl class="agent-facts"><div><dt>Created</dt><dd>{{date(selected.created_at)}}</dd></div><div><dt>Last seen</dt><dd>{{date(selected.last_seen_at)}}</dd></div></dl></article><aside class="panel agent-admin"><h3>Administration</h3><p class="muted">Manage this durable execution target.</p><button @click="startRename">Rename</button><button class="danger-button" :disabled="selected.revoked" @click="revoke">Revoke agent</button></aside></div><aside class="agent-warning"><strong>Native execution trust boundary</strong><p>Native execution uses the OS account running the Agent and is not sandboxed. Workspace root is an organizational/work-directory boundary, not a security boundary.</p></aside></template>
<div v-else-if="!loading" class="empty-state panel"><h2>No Remote Agents enrolled</h2><p>Enroll a user-controlled machine to make it available as a Workspace execution target.</p><button class="primary" @click="enroll">Enroll agent</button></div>
<div v-if="renameOpen" class="rename-form panel"><label for="agent-name">Agent name</label><input id="agent-name" v-model="rename" maxlength="120" @keyup.enter="saveRename"><div><button @click="renameOpen=false">Cancel</button><button class="primary" :disabled="saving" @click="saveRename">{{saving?'Saving…':'Save name'}}</button></div></div></section></template>
