<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { request } from '../api'
import { useAuthStore } from '../stores/auth'

const statuses = [{ id: 'backlog', label: 'Backlog' }, { id: 'ready', label: 'Ready' }, { id: 'doing', label: 'Doing' }, { id: 'done', label: 'Done' }]
const route = useRoute(); const router = useRouter(); const auth = useAuthStore()
const tasks = ref([]); const projects = ref([]); const project = ref(null); const selected = ref(null)
const loading = ref(true); const error = ref(''); const mutationError = ref(''); const busy = ref(false)
const projectFilter = ref(''); const priorityFilter = ref(''); const tagFilter = ref(''); const showDropped = ref(false)
const createOpen = ref(false); const createStatus = ref('backlog'); const createProject = ref(''); const createError = ref('')
const draft = ref({ title: '', priority: 'normal', tags: '', context: '', intended_direction: '' })
const draggingId = ref(null); const dropTarget = ref(null)
const isProject = computed(() => Boolean(route.params.project)); const scopeLabel = computed(() => project.value?.name || 'All tasks'); const selectedId = computed(() => route.params.taskId)
const visibleTasks = computed(() => tasks.value.filter((task) => (showDropped.value || task.status !== 'dropped') && (!projectFilter.value || task.project?.slug === projectFilter.value) && (!priorityFilter.value || task.priority === priorityFilter.value) && (!tagFilter.value || task.tags?.some((tag) => tag.toLowerCase().includes(tagFilter.value.toLowerCase())))))
const columns = computed(() => statuses.map((status) => ({ ...status, tasks: visibleTasks.value.filter((task) => task.status === status.id).sort((a, b) => a.position - b.position || a.id - b.id) })))

async function loadSelected(id) { try { selected.value = await request(`/tasks/${id}`, {}, auth.token); draft.value = { title: selected.value.title, priority: selected.value.priority || 'normal', tags: selected.value.tags?.join(', ') || '', context: selected.value.context || '', intended_direction: selected.value.intended_direction || '' } } catch (e) { mutationError.value = e.message; selected.value = null } }
async function load() { loading.value = true; error.value = ''; try { const [data, projectData] = await Promise.all([request(isProject.value ? `/projects/${route.params.project}/tasks?summary=true` : '/tasks?summary=true', {}, auth.token), request('/projects', {}, auth.token)]); tasks.value = data; projects.value = projectData; project.value = isProject.value ? projectData.find((item) => item.slug === route.params.project) || data[0]?.project : null; if (isProject.value) createProject.value = route.params.project; if (selectedId.value) await loadSelected(selectedId.value); else selected.value = null } catch (e) { error.value = e.message } finally { loading.value = false } }
function taskPath(task) { return isProject.value ? `/projects/${task.project.slug}/tasks/${task.id}` : `/tasks/${task.id}` }
function openTask(task) { router.push(taskPath(task)) }
function closeTask() { router.push(isProject.value ? `/projects/${route.params.project}/tasks` : '/tasks') }
function beginCreate(status = 'backlog') { createOpen.value = true; createStatus.value = status; createError.value = ''; draft.value = { title: '', priority: 'normal', tags: '', context: '', intended_direction: '' }; if (!createProject.value) createProject.value = project.value?.slug || projects.value[0]?.slug || '' }
function payloadFromDraft() { return { title: draft.value.title.trim(), status: createStatus.value, priority: draft.value.priority, tags: draft.value.tags.split(',').map((tag) => tag.trim()).filter(Boolean), context: draft.value.context, intended_direction: draft.value.intended_direction } }
async function createTask() { if (!draft.value.title.trim() || !createProject.value) return; busy.value = true; createError.value = ''; try { const task = await request(`/projects/${createProject.value}/tasks`, { method: 'POST', body: JSON.stringify(payloadFromDraft()) }, auth.token); tasks.value.push(task); createOpen.value = false; openTask(task) } catch (e) { createError.value = e.message } finally { busy.value = false } }
async function updateTask(changes) { if (!selected.value) return; const previous = { ...selected.value }; busy.value = true; mutationError.value = ''; Object.assign(selected.value, changes); try { const updated = await request(`/tasks/${selected.value.id}`, { method: 'PATCH', body: JSON.stringify(changes) }, auth.token); Object.assign(selected.value, updated); const index = tasks.value.findIndex((task) => task.id === selected.value.id); if (index >= 0) tasks.value[index] = { ...tasks.value[index], ...updated } } catch (e) { Object.assign(selected.value, previous); mutationError.value = e.message; await loadSelected(selected.value.id) } finally { busy.value = false } }
function changeStatus(status) { const position = status === selected.value?.status ? selected.value.position : Math.max(0, ...tasks.value.filter((task) => task.status === status).map((task) => task.position || 0)) + 1000; updateTask({ status, position }) }
function positionFor(list, index) { const before = list[index - 1]?.position; const after = list[index]?.position; if (before === undefined) return (after || 1000) - 1000; if (after === undefined) return before + 1000; return Math.floor((before + after) / 2) }
async function dropAt(status, index) { if (!draggingId.value) return; const task = tasks.value.find((item) => item.id === draggingId.value); const target = columns.value.find((column) => column.id === status); if (!task || !target) return; const oldTasks = tasks.value.map((item) => ({ ...item })); const remaining = target.tasks.filter((item) => item.id !== task.id); const position = positionFor(remaining, index); const oldStatus = task.status; const oldPosition = task.position; task.status = status; task.position = position; dropTarget.value = null; draggingId.value = null; mutationError.value = ''; try { const updated = await request(`/tasks/${task.id}`, { method: 'PATCH', body: JSON.stringify({ status, position }) }, auth.token); Object.assign(task, updated); if (selected.value?.id === task.id) Object.assign(selected.value, updated) } catch (e) { tasks.value = oldTasks; mutationError.value = `Could not move “${task.title}”: ${e.message}`; task.status = oldStatus; task.position = oldPosition } }
function dragStart(event, task) { draggingId.value = task.id; event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/task-id', String(task.id)) }
function dragEnd() { draggingId.value = null; dropTarget.value = null }
function dragOver(status, index) { dropTarget.value = { status, index } }
async function moveSelected(direction) { if (!selected.value) return; const column = columns.value.find((item) => item.id === selected.value.status); const index = column.tasks.findIndex((item) => item.id === selected.value.id); draggingId.value = selected.value.id; await dropAt(column.id, Math.max(0, Math.min(column.tasks.length, index + direction))) }
watch(() => route.fullPath, () => { if (selectedId.value) loadSelected(selectedId.value); else selected.value = null })
onMounted(load)
</script>

<template>
  <section class="board-page">
    <div class="board-heading"><div><p class="eyebrow">Task board</p><h1>{{ scopeLabel }}</h1></div><button class="primary" @click="beginCreate()">+ New task</button></div>
    <form class="board-filters" @submit.prevent="load"><label v-if="!isProject">Project<select v-model="projectFilter"><option value="">All projects</option><option v-for="item in projects" :key="item.id" :value="item.slug">{{ item.name }}</option></select></label><label>Priority<select v-model="priorityFilter"><option value="">Any priority</option><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></label><label>Tag<input v-model="tagFilter" placeholder="Filter tag" /></label><label class="check"><input v-model="showDropped" type="checkbox" /> Show dropped</label></form>
    <p v-if="error" class="error" role="alert">{{ error }} <button @click="load">Retry</button></p><p v-if="mutationError" class="error" role="alert">{{ mutationError }}</p><p v-if="loading" class="muted" role="status">Loading tasks…</p>
    <div v-else class="board" aria-label="Task board"><article v-for="column in columns" :key="column.id" class="board-column" @dragover.prevent="dragOver(column.id, column.tasks.length)" @drop.prevent="dropAt(column.id, column.tasks.length)"><header><h2>{{ column.label }}</h2><span>{{ column.tasks.length }}</span><button class="column-add" :aria-label="`Create task in ${column.label}`" @click="beginCreate(column.id)">+</button></header><div v-if="!column.tasks.length" class="column-empty" :class="{ 'drop-placeholder': dropTarget?.status === column.id }">Drop here or create a task.<button @click="beginCreate(column.id)">Create one</button></div><div v-else class="card-stack"><div v-for="(task, index) in column.tasks" :key="task.id"><div v-if="dropTarget?.status === column.id && dropTarget.index === index" class="drop-placeholder" aria-label="Drop task here">Insert task here</div><button class="task-card" :class="{ dragging: draggingId === task.id }" draggable="true" @dragstart="dragStart($event, task)" @dragend="dragEnd" @dragover.stop.prevent="dragOver(column.id, index)" @drop.stop.prevent="dropAt(column.id, index)" @click="openTask(task)"><strong>{{ task.title }}</strong><span v-if="!isProject" class="card-project">{{ task.project.name }}</span><span v-if="task.priority && task.priority !== 'normal'" class="priority" :class="`priority-${task.priority}`">{{ task.priority }}</span><span v-if="task.tags?.length" class="tags">{{ task.tags.join(' · ') }}</span></button></div><div v-if="dropTarget?.status === column.id && dropTarget.index === column.tasks.length" class="drop-placeholder" aria-label="Drop task here">Insert task here</div></div></article></div>
    <div v-if="showDropped && visibleTasks.some((task) => task.status === 'dropped')" class="dropped-list"><h2>Dropped</h2><button v-for="task in visibleTasks.filter((item) => item.status === 'dropped')" :key="task.id" @click="openTask(task)">{{ task.title }}</button></div>
    <div v-if="createOpen" class="create-bar"><form @submit.prevent="createTask"><label>Title<input v-model="draft.title" autofocus placeholder="What needs doing?" required /></label><label>Project<select v-model="createProject" :disabled="isProject"><option value="" disabled>Choose project</option><option v-for="item in projects" :key="item.id" :value="item.slug">{{ item.name }}</option></select></label><label>Priority<select v-model="draft.priority"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></label><label>Tags<input v-model="draft.tags" placeholder="comma separated" /></label><label>Context<textarea v-model="draft.context" rows="2" placeholder="Useful context (optional)" /></label><label>Intended direction<textarea v-model="draft.intended_direction" rows="2" placeholder="What should happen? (optional)" /></label><p class="create-status">{{ createStatus }}</p><div><button class="primary" :disabled="busy">Create task</button><button type="button" @click="createOpen = false">Cancel</button></div></form><p v-if="createError" class="error">{{ createError }}</p></div>
    <aside v-if="selected" class="detail-pane" aria-label="Task details"><button class="close" aria-label="Close task details" @click="closeTask">×</button><p class="eyebrow">Task detail</p><h2>{{ selected.title }}</h2><p v-if="mutationError" class="error">{{ mutationError }}</p><label>Title<input :value="selected.title" @change="updateTask({ title: $event.target.value })" /></label><label>Status<select :value="selected.status" @change="changeStatus($event.target.value)"><option v-for="item in [...statuses, { id: 'dropped', label: 'Dropped' }]" :key="item.id" :value="item.id">{{ item.label }}</option></select></label><div class="order-controls"><span>Order</span><button @click="moveSelected(-1)">Move up</button><button @click="moveSelected(1)">Move down</button></div><label>Priority<select :value="selected.priority || 'normal'" @change="updateTask({ priority: $event.target.value })"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></label><p class="field-label">Project</p><p class="readonly-field">{{ selected.project.name }}</p><label>Tags<input :value="selected.tags?.join(', ')" placeholder="comma separated" @change="updateTask({ tags: $event.target.value.split(',').map((tag) => tag.trim()).filter(Boolean) })" /></label><section class="prose-field"><h3>Context</h3><textarea :value="selected.context || ''" rows="4" @change="updateTask({ context: $event.target.value })" /></section><section class="prose-field"><h3>Intended direction</h3><textarea :value="selected.intended_direction || ''" rows="4" @change="updateTask({ intended_direction: $event.target.value })" /></section><section class="related"><h3>Related notes</h3><p v-if="!selected.related_notes?.length" class="muted">No related notes.</p><a v-for="note in selected.related_notes" :key="note.id" href="#">{{ note.title }}</a></section></aside>
  </section>
</template>
