<script setup>
import { onMounted, ref } from 'vue'; import { request } from '../api'; import { useAuthStore } from '../stores/auth'
const auth=useAuthStore(); const workspaces=ref([]); const selected=ref(null); const creating=ref(false); const loading=ref(true); const error=ref(''); const form=ref({label:'',environment:'ubuntu-24.04',ttl_seconds:7200})
async function load(){try{const data=await request('/workspaces?limit=100',{},auth.token);workspaces.value=data.workspaces||[];if(workspaces.value[0])open(workspaces.value[0])}catch(e){error.value=e.message}finally{loading.value=false}}
async function open(item){try{selected.value=await request(`/workspaces/${encodeURIComponent(item.ref)}`,{},auth.token)}catch(e){error.value=e.message}}
async function create(){creating.value=true;try{const item=await request('/workspaces',{method:'POST',body:JSON.stringify(form.value)},auth.token);workspaces.value.unshift(item);selected.value=item;form.value={label:'',environment:'ubuntu-24.04',ttl_seconds:7200}}catch(e){error.value=e.message}finally{creating.value=false}}
async function destroy(){if(!selected.value)return;try{await request(`/workspaces/${encodeURIComponent(selected.value.ref)}`,{method:'DELETE'},auth.token);workspaces.value=workspaces.value.filter(w=>w.ref!==selected.value.ref);selected.value=null}catch(e){error.value=e.message}}
onMounted(load)
</script>
<template><section class="surface-page"><header class="page-heading"><div><h1>Workspaces</h1><p>Disposable Linux environments for model-driven engineering</p></div><button class="primary" @click="creating=!creating">New workspace</button></header><form v-if="creating" class="panel inline-form" @submit.prevent="create"><input v-model="form.label" placeholder="Workspace label" required><select v-model="form.environment"><option>ubuntu-24.04</option><option>linux</option></select><button class="primary">Create</button></form><div class="toolbar"><span>Ready and recent</span></div><p v-if="loading" class="muted">Loading workspaces…</p><div v-else class="workspace-table"><button v-for="item in workspaces" :key="item.ref" class="workspace-row" :class="{selected:selected?.ref===item.ref}" @click="open(item)"><strong>{{item.ref}}</strong><strong>{{item.label || 'Unnamed workspace'}}</strong><span class="state-ready">{{item.state}}</span><span>{{item.environment}}</span><span>{{new Date(item.last_activity_at).toLocaleString()}}</span></button></div><article v-if="selected" class="workspace-detail panel"><span class="meta">{{selected.ref}}</span><h2>{{selected.label || 'Unnamed workspace'}}</h2><p class="meta">{{selected.state}} · {{selected.environment}} · {{selected.architecture}} · {{selected.workspace_root}}</p><div class="relations"><strong>Credentials</strong><span v-for="binding in selected.credential_bindings" :key="binding.ref" class="pill blue">{{binding.ref}} · {{binding.kind}}</span><span v-if="!selected.credential_bindings?.length" class="muted">None</span></div><h3>Recent execution</h3><div class="execution-summary">Workspace runtime is ready for authenticated execution.</div><button class="danger" @click="destroy">Destroy workspace</button></article><p v-if="error" class="error">{{error}}</p></section></template>
