<script setup>
import { onMounted, ref } from 'vue'; import { request } from '../api'; import { useAuthStore } from '../stores/auth'
import { useLiveInvalidation } from '../useLiveInvalidation'
const auth=useAuthStore(); const workspaces=ref([]); const selected=ref(null); const loading=ref(true); const error=ref('')
async function load(){try{const data=await request('/workspaces?limit=100',{},auth.token);workspaces.value=data.workspaces||[];if(workspaces.value[0])open(workspaces.value[0])}catch(e){error.value=e.message}finally{loading.value=false}}
async function open(item){try{selected.value=await request(`/workspaces/${encodeURIComponent(item.ref)}`,{},auth.token)}catch(e){error.value=e.message}}
async function destroy(){if(!selected.value)return;try{await request(`/workspaces/${encodeURIComponent(selected.value.ref)}`,{method:'DELETE'},auth.token);workspaces.value=workspaces.value.filter(w=>w.ref!==selected.value.ref);selected.value=null}catch(e){error.value=e.message}}
onMounted(load); useLiveInvalidation(load, ['workspace.updated', 'workspace_execution.updated', 'file.created'])
</script>
<template><section class="surface-page"><header class="page-heading"><div><h1>Workspaces</h1><p>Transient execution environments for model-driven engineering</p></div></header><div class="toolbar"><span>Ready and recent</span></div><p v-if="loading" class="muted">Loading workspaces…</p><div v-else-if="workspaces.length" class="workspace-table"><button v-for="item in workspaces" :key="item.ref" class="workspace-row" :class="{selected:selected?.ref===item.ref}" @click="open(item)"><strong>{{item.ref}}</strong><strong>{{item.label || 'Unnamed workspace'}}</strong><span class="state-ready">{{item.state}}</span><span>{{item.environment}}</span><span>{{new Date(item.last_activity_at).toLocaleString()}}</span></button></div><article v-else class="empty-state panel"><h2>No active Workspaces</h2><p>Workspaces are transient execution environments created by model clients. Hosted or Remote Agent targets appear here while work is active.</p></article><article v-if="selected" class="workspace-detail panel"><span class="meta">{{selected.ref}}</span><h2>{{selected.label || 'Unnamed workspace'}}</h2><p class="meta">{{selected.state}} · {{selected.environment}} · {{selected.architecture}} · {{selected.workspace_root}}</p><div class="relations"><strong>Credentials</strong><span v-for="binding in selected.credential_bindings" :key="binding.ref" class="pill blue">{{binding.ref}} · {{binding.kind}}</span><span v-if="!selected.credential_bindings?.length" class="muted">None</span></div><h3>Recent execution</h3><div class="execution-summary">Workspace runtime is available to model-driven tools. Browser execution controls are not exposed here.</div><button class="danger" @click="destroy">Destroy workspace</button></article><p v-if="error" class="error">{{error}}</p></section></template>
